### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by khizar1556** [MoboPlayer/MoboVideoViewLibrary#1]
When i run this app destroyed and give this error
FATAL EXCEPTION: main
    Process: com.apical.testmoboplayer, PID: 25523
    java.lang.NoClassDefFoundError: com.clov4r.moboplayer.android.rtmp.MoboVideoView$10
        at com.clov4r.moboplayer.android.rtmp.MoboVideoView.<init>(MoboVideoView.java:1625)
        at com.clov4r.moboplayer.android.rtmp.MainActivity.download(MainActivity.java:448)
        at com.clov4r.moboplayer.android.rtmp.MainActivity.onCreate(MainActivity.java:72)
        at android.app.Activity.performCreate(Activity.java:6877)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.access$1100(ActivityThread.java:223)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7223)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by khizar1556** [comment]
@clov4r-lyw @yykxlgh @jnclov4r  can you please clear this ?
